// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug: Log environment variable status (without exposing full key)
if (import.meta.env.DEV) {
  console.log('🔍 Supabase Configuration:');
  console.log('   URL:', SUPABASE_URL || '❌ NOT SET');
  console.log('   Key:', SUPABASE_PUBLISHABLE_KEY ? `✅ Set (${SUPABASE_PUBLISHABLE_KEY.length} chars)` : '❌ NOT SET');
  if (SUPABASE_PUBLISHABLE_KEY) {
    // Check if key starts with quotes (common .env issue)
    if (SUPABASE_PUBLISHABLE_KEY.startsWith('"') || SUPABASE_PUBLISHABLE_KEY.startsWith("'")) {
      console.warn('⚠️ Key appears to have quotes - this may cause issues. Remove quotes from .env file.');
    }
  }
}

// Validate environment variables
if (!SUPABASE_URL) {
  console.error('❌ VITE_SUPABASE_URL is not set. Please add it to your .env file.');
  console.error('   Expected: VITE_SUPABASE_URL=https://axnpahnmktvtmnkrgtba.supabase.co');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ VITE_SUPABASE_PUBLISHABLE_KEY is not set. Please add it to your .env file.');
  console.error('   Get your anon/publishable key from: https://supabase.com/dashboard/project/axnpahnmktvtmnkrgtba/settings/api');
} else if (SUPABASE_PUBLISHABLE_KEY.length < 50) {
  // Modern publishable keys (sb_publishable_...) are shorter than legacy anon keys
  // Check for both formats
  const isModernKey = SUPABASE_PUBLISHABLE_KEY.startsWith('sb_publishable_');
  const isLegacyKey = SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ');
  
  if (!isModernKey && !isLegacyKey) {
    console.warn('⚠️ VITE_SUPABASE_PUBLISHABLE_KEY format appears invalid.');
    console.warn('   Should start with "sb_publishable_" (modern) or "eyJ" (legacy anon key)');
    console.warn('   Get your key from: https://supabase.com/dashboard/project/flndlrgxxnlhuuusargv/settings/api');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL || '', SUPABASE_PUBLISHABLE_KEY || '', {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
